create table if not exists public.contact_inquiries (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  message text not null,
  created_at timestamptz not null default now()
);

-- Optional: keep storage private by default.
alter table public.contact_inquiries enable row level security;
